name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    uses: matt-riley/matt-riley-ci/.github/workflows/cloudflare-pages-deploy.yml@0b59f15c4f9b796fc54dcc6ee9ca0ce84292e4a8 # main
    with:
      project-name: mysite
      package-manager: pnpm
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
